### ISSUE TITLE
Setting default values for connector connections

### ISSUE THREAD

**Issue by abeykoon** [wso2/integration-studio#15]
**Description:**

It does not set the default value in the drop down . 
Also issue [1] is seen in the file connector because of this issue. 

[1]. https://github.com/wso2-extensions/esb-connector-file/issues/141

**Comment by tharakamd** [comment]
When adding a default value to a field in a connector, the `required` parameter should be set to `true` in the `uischema` file. There's no requirement to show a default value if that parameter is not required. Please refer to the example of how to add a default value in `uischema` file.

```json

{
  "type": "attribute",
  "value": {
    "name": "from",
    "displayName": "From",
    "inputType": "stringOrExpression",
    "defaultValue": "abc@foo.com",
    "required": "true",
    "helpTip": "The 'From' address of the message sender"
  }
}
```

And also, the connector connection default value not showing issue is fixed with the PR https://github.com/wso2/integration-studio/pull/716
